name: test
on: push
jobs:
  is-this-really-working:
    env:
      GCC_TOOLS_PATH: tools/arm-none-eabi-gcc-10-2020-q4
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # Store the arm compilers in the cache to speed up builds
      - name: Cache arm-none-eabi-gcc tools
        id: cache-arm-gcc
        uses: actions/cache@v1
        with:
          path: ${{ env.GCC_TOOLS_PATH }}
          key: ${{ runner.os }}-arm-gcc-10-2020-q4

      # Get the arm-non-eabi-gcc toolchain   
      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        if: steps.cache-arm-gcc.outputs.cache-hit != 'true'
        with:
            release: '10-2020-q4' # The arm-none-eabi-gcc release to use.
            directory: ${{ env.TOOLS_PATH }}
      - name: build
        run: ${{ env.TOOLS_PATH }}/bin/arm-none-eabi-gcc -v       
