name: test
on: push
jobs:
  is-this-really-working:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # Store the arm compilers in the cache to speed up builds
      - name: Cache arm-none-eabi-gcc tools
        id: cache-arm-gcc
        uses: actions/cache@v1
        with:
          path: $HOME/arm-none-eabi-gcc-10-2020-q4
          key: ${{ runner.os }}-arm-gcc-10-2020-q4

      # Get the arm-non-eabi-gcc toolchain   
      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        if: steps.cache-arm-gcc.outputs.cache-hit != 'true'
        with:
            release: '10-2020-q4' # The arm-none-eabi-gcc release to use.
            directory: $HOME/arm-none-eabi-gcc-10-2020-q4
      - name: build
        run: $HOME/arm-none-eabi-gcc-10-2020-q4/bin/arm-none-eabi-gcc       
